services:
  storybook:
    container_name: test_storybook
    build:
      context: .
      dockerfile_inline: |
        FROM "node:${NODE_VERSION}"
        RUN apt-get update && apt-get install -y build-essential
        RUN npm i http-server -g
    working_dir: /visual-regression
    volumes:
      - type: bind
        source: ./storybook-static
        target: /visual-regression/storybook-static
    environment:
      - NODE_VERSION=${NODE_VERSION}
    ports:
      - "6060:6060"
    entrypoint: npx http-server storybook-static -p 6060 -s
  cypress:
    container_name: test_cypress
    build:
      context: .
      dockerfile_inline: |
        FROM "cypress/included:${CYPRESS_VERSION}"
    working_dir: /test-repo/packages/storybook
    volumes:
      - ./:/test-repo
    environment:
      - CYPRESS_baseUrl=http://storybook:6060
      - CYPRESS_INSTALL_BINARY=0
      - CYPRESS_VERSION=${CYPRESS_VERSION}
      - CYPRESS_updateSnapshots=${IS_UPDATE}
    depends_on:
      - storybook
